name: Manually triggered

on:
  workflow_dispatch:
    inputs:
      TAG:
        description: Tag to build image
        required: true
  release:
    tags:
      - '*'

jobs:
  release:
    name: Build & push image
    runs-on: ubuntu-latest
    steps:
      - run: echo "TAG ${{ github.event.inputs.TAG }}"
      - run: echo "GITHUB REF ${GITHUB_REF}"
      - run: echo "release tags ${GITHUB_REF/refs\/tags\/}"
