name: Manually triggered

on:
  workflow_dispatch:
    inputs:
      TAG:
        description: Tag to build image
        required: true
  release:
    tags:
      - '*'

jobs:
  release:
    name: Build & push image
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "INPUT_TAG=${{ github.event.inputs.TAG }}" >> $GITHUB_ENV
      - run: |
          echo "TAG=${INPUT_TAG:-${GITHUB_REF/refs\/tags\/}}" >> $GITHUB_ENV
      - run: echo "FINAL TAG ${TAG}"
      - run: cat $GITHUB_ENV
